# -*- coding: utf-8 -*-
"""p2-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rdbKgYgG9M8g7syO3BxkGFbehN0DQ4P0
"""

# Install dependencies
!pip install -q transformers datasets peft torch accelerate evaluate scikit-learn transformers_stream_generator

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
import numpy as np
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass
import copy
from tqdm.auto import tqdm
import warnings
warnings.filterwarnings('ignore')

# HuggingFace imports
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments
)
from peft import (
    LoraConfig,
    get_peft_model,
    TaskType,
    PeftModel
)
from datasets import load_dataset
import evaluate

# Set device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

# Model selection
# MODEL_NAME = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
MODEL_NAME = "Qwen/Qwen2.5-0.5B"

print(f"Loading model: {MODEL_NAME}")

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# Load base model in bf16
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    trust_remote_code=True
)

# Configure LoRA
lora_config = LoraConfig(
    r=16,  # Low-rank dimension
    lora_alpha=32,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],  # Attention modules
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)

# Apply LoRA
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# Freeze base model (only LoRA params are trainable) - NSP in LoRA subspace to reduce complexity
for name, param in model.named_parameters():
    if 'lora' not in name:
        param.requires_grad = False

# Load SQuAD v1.1
squad = load_dataset("squad", split="validation")

# Sample subsets for efficiency
RETENTION_SIZE = 100
EDIT_SIZE = 50
SAFETY_SIZE = 30

# Create splits
np.random.seed(42)
indices = np.random.permutation(len(squad))

retention_indices = indices[:RETENTION_SIZE]
edit_indices = indices[RETENTION_SIZE:RETENTION_SIZE + EDIT_SIZE]
safety_indices = indices[RETENTION_SIZE + EDIT_SIZE:RETENTION_SIZE + EDIT_SIZE + SAFETY_SIZE]

retention_set = squad.select(retention_indices)
edit_set = squad.select(edit_indices)
safety_set = squad.select(safety_indices)

print(f"Retention set: {len(retention_set)} examples")
print(f"Edit set: {len(edit_set)} examples")
print(f"Safety set: {len(safety_set)} examples")

## Example format
# print("\nExample QA pair:")
# print(f"Q: {retention_set[0]['question']}")
# print(f"A: {retention_set[0]['answers']['text'][0]}")

def format_qa_prompt(question: str, context: str = "") -> str:
    """Format question as a prompt for the model."""
    if context:
        return f"Context: {context}\n\nQuestion: {question}\n\nAnswer:"
    return f"Question: {question}\n\nAnswer:"

def extract_answer(text: str) -> str:
    """Extract answer from model output."""
    # Simple heuristic: take text after "Answer:" and before newline
    if "Answer:" in text:
        answer = text.split("Answer:")[-1].strip()
    else:
        answer = text.strip()

    # Take first sentence or up to 50 tokens
    answer = answer.split('\n')[0].strip()
    tokens = answer.split()
    if len(tokens) > 50:
        answer = ' '.join(tokens[:50])

    return answer

def generate_answer(model, tokenizer, question: str, context: str = "", max_new_tokens: int = 50) -> str:
    """Generate answer for a question."""
    prompt = format_qa_prompt(question, context)
    inputs = tokenizer(prompt, return_tensors="pt", padding=True, truncation=True, max_length=512)
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    full_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return extract_answer(full_text)

# Load exact match and F1 metrics
squad_metric = evaluate.load("squad")

def compute_em_f1(model, tokenizer, dataset) -> Dict[str, float]:
    """Compute exact match and F1 scores on a dataset."""
    predictions = []
    references = []

    for item in tqdm(dataset, desc="Evaluating", leave=False):
        pred_answer = generate_answer(
            model, tokenizer,
            item['question'],
            item['context']
        )

        predictions.append({
            'id': item['id'],
            'prediction_text': pred_answer
        })

        references.append({
            'id': item['id'],
            'answers': item['answers']
        })

    results = squad_metric.compute(predictions=predictions, references=references)
    return {
        'exact_match': results['exact_match'],
        'f1': results['f1']
    }

print("Utilities loaded successfully")

print("baseline metrics\n")

# Evaluate on retention set
print("Retention Set:")
baseline_retention = compute_em_f1(model, tokenizer, retention_set)
print(f"  EM: {baseline_retention['exact_match']:.2f}")
print(f"  F1: {baseline_retention['f1']:.2f}\n")

# Evaluate on edit set
print("Edit Set:")
baseline_edit = compute_em_f1(model, tokenizer, edit_set)
print(f"  EM: {baseline_edit['exact_match']:.2f}")
print(f"  F1: {baseline_edit['f1']:.2f}\n")

# Evaluate on safety set
print("Safety Set:")
baseline_safety = compute_em_f1(model, tokenizer, safety_set)
print(f"  EM: {baseline_safety['exact_match']:.2f}")
print(f"  F1: {baseline_safety['f1']:.2f}")

def get_lora_params(model) -> List[torch.Tensor]:
    """Extract all LoRA parameters from model."""
    lora_params = []
    for name, param in model.named_parameters():
        if 'lora' in name and param.requires_grad:
            lora_params.append(param)
    return lora_params

def flatten_gradients(params: List[torch.Tensor]) -> torch.Tensor:
    """Flatten gradients from parameter list into 1D vector."""
    grads = []
    for p in params:
        if p.grad is not None:
            grads.append(p.grad.detach().flatten())
    return torch.cat(grads)

def unflatten_gradients(flat_grad: torch.Tensor, params: List[torch.Tensor]):
    """Unflatten 1D gradient vector back to parameter shapes."""
    offset = 0
    for p in params:
        numel = p.numel()
        p.grad = flat_grad[offset:offset + numel].view_as(p).clone()
        offset += numel

def compute_retention_basis(model, tokenizer, retention_set, k: int = 20) -> torch.Tensor:
    """
    Compute low-rank basis spanning retention gradient subspace.

    Args:
        model: PEFT model with LoRA adapters
        tokenizer: Tokenizer
        retention_set: Dataset to preserve
        k: Rank of subspace (number of principal components)

    Returns:
        U_k: Orthonormal basis matrix (d_adapter × k)
    """
    print(f"Building retention basis (k={k})...")

    lora_params = get_lora_params(model)
    d_adapter = sum(p.numel() for p in lora_params)
    print(f"Total LoRA parameters: {d_adapter:,}")

    # Collect gradients
    G = []  # Will be N × d_adapter

    model.train()
    for item in tqdm(retention_set, desc="Computing retention gradients"):
        # Format input
        prompt = format_qa_prompt(item['question'], item['context'])
        target = item['answers']['text'][0]
        full_text = prompt + " " + target

        # Tokenize
        inputs = tokenizer(full_text, return_tensors="pt", truncation=True, max_length=512)
        inputs = {k: v.to(model.device) for k, v in inputs.items()}

        # Forward pass
        outputs = model(**inputs, labels=inputs['input_ids'])
        loss = outputs.loss

        # Backward pass
        model.zero_grad()
        loss.backward()

        # Collect flattened gradient
        g = flatten_gradients(lora_params)
        G.append(g.cpu())

    # Stack into matrix: N × d_adapter
    G = torch.stack(G)
    print(f"Gradient matrix shape: {G.shape}")

    # Compute truncated SVD: G ≈ U_k Σ_k V_k^T
    # We only need U_k (left singular vectors)
    U, S, Vh = torch.linalg.svd(G, full_matrices=False)

    # Take top k components
    k = min(k, U.shape[1])  # Handle case where k > rank
    U_k = Vh[:k, :].T  # d_adapter × k

    print(f"Retained singular values: {S[:k].tolist()[:5]}...")
    print(f"Basis shape: {U_k.shape}")
    print(f"Explained variance ratio: {(S[:k]**2).sum() / (S**2).sum():.4f}")

    return U_k.to(model.device)

# Build the basis
retention_basis = compute_retention_basis(model, tokenizer, retention_set, k=20)

def project_to_null_space(grad_flat: torch.Tensor, basis: torch.Tensor) -> torch.Tensor:
    """
    Project gradient to null space of retention basis.

    g_proj = g - U_k (U_k^T g)

    Args:
        grad_flat: Flattened gradient vector (d_adapter,)
        basis: Orthonormal basis U_k (d_adapter × k)

    Returns:
        Projected gradient (d_adapter,)
    """
    # Project onto subspace
    projection = basis @ (basis.T @ grad_flat)

    # Remove projection (keep orthogonal component)
    grad_projected = grad_flat - projection

    return grad_projected

def compute_edit_gradient(model, tokenizer, item: Dict) -> torch.Tensor:
    """
    Compute gradient for a single edit example.

    Args:
        model: PEFT model
        tokenizer: Tokenizer
        item: SQuAD-format dict with question, context, answers

    Returns:
        Flattened gradient vector
    """
    lora_params = get_lora_params(model)

    # Format input
    prompt = format_qa_prompt(item['question'], item['context'])
    target = item['answers']['text'][0]
    full_text = prompt + " " + target

    # Tokenize
    inputs = tokenizer(full_text, return_tensors="pt", truncation=True, max_length=512)
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    # Forward + backward
    model.zero_grad()
    outputs = model(**inputs, labels=inputs['input_ids'])
    loss = outputs.loss
    loss.backward()

    # Extract gradient
    grad = flatten_gradients(lora_params)

    return grad

## Safety Module
def check_output_safety(text: str) -> Tuple[bool, str]:
    """Check if generated text is degenerate or invalid."""
    text_stripped = text.strip()

    # Check for output collapse
    if len(text_stripped) < 3:
        return False, "Output too short (degenerate)"

    # Check for repetitive output (sign of degradation)
    words = text_stripped.split()
    if len(words) > 5:
        # Check if same word repeats more than 50% of output
        word_counts = {}
        for word in words:
            word_counts[word] = word_counts.get(word, 0) + 1
        max_count = max(word_counts.values())
        if max_count / len(words) > 0.5:
            return False, "Repetitive output detected"

    return True, "OK"

def check_behavioral_safety(
    model,
    tokenizer,
    safety_set,
    baseline_em: float,
    baseline_f1: float,
    em_threshold: float = 10.0,  # Allow max 10 point EM drop
    f1_threshold: float = 10.0   # Allow max 10 point F1 drop
) -> Tuple[bool, str]:
    """
    Check if model performance on safety-critical examples is preserved.
    This prevents edits that would cause performance degradation.

    Args:
        model: Model after edit
        tokenizer: Tokenizer
        safety_set: Critical QA examples to check performance
        baseline_em: Baseline exact match score
        baseline_f1: Baseline F1 score
        em_threshold: Max allowed EM drop (in percentage points)
        f1_threshold: Max allowed F1 drop (in percentage points)

    Returns:
        (is_safe, reason)
    """
    current_metrics = compute_em_f1(model, tokenizer, safety_set)
    current_em = current_metrics['exact_match']
    current_f1 = current_metrics['f1']

    em_drop = baseline_em - current_em
    f1_drop = baseline_f1 - current_f1

    if em_drop > em_threshold:
        return False, f"Performance degraded: EM dropped by {em_drop:.2f} points (threshold: {em_threshold})"

    if f1_drop > f1_threshold:
        return False, f"Performance degraded: F1 dropped by {f1_drop:.2f} points (threshold: {f1_threshold})"

    return True, "Performance preserved"

## Batch Processing
@dataclass
class EditCandidate:
    """Represents a single edit candidate."""
    item: Dict
    gradient: torch.Tensor
    projected_gradient: torch.Tensor
    score: float = 0.0
    safe: bool = True
    safety_reason: str = "Not checked"

def backup_lora_state(model) -> Dict:
    """Backup current LoRA adapter weights."""
    state = {}
    for name, param in model.named_parameters():
        if 'lora' in name and param.requires_grad:
            state[name] = param.data.clone()
    return state

def restore_lora_state(model, state: Dict):
    """Restore LoRA adapter weights from backup."""
    for name, param in model.named_parameters():
        if name in state:
            param.data.copy_(state[name])

def apply_projected_update(
    model,
    projected_grad: torch.Tensor,
    lr: float = 1e-5
):
    """
    Apply projected gradient update to LoRA parameters.

    Args:
        model: PEFT model
        projected_grad: Flattened projected gradient
        lr: Learning rate for update
    """
    lora_params = get_lora_params(model)
    unflatten_gradients(projected_grad, lora_params)

    # Apply gradient descent step
    with torch.no_grad():
        for p in lora_params:
            if p.grad is not None:
                p.data.add_(p.grad, alpha=-lr)

def compute_adapter_drift(state_before: Dict, state_after: Dict) -> float:
    """Compute L2 norm of parameter change."""
    total_drift = 0.0
    for name in state_before:
        if name in state_after:
            diff = state_after[name] - state_before[name]
            total_drift += (diff ** 2).sum().item()
    return np.sqrt(total_drift)

def score_edit(
    model,
    tokenizer,
    edit_item: Dict,
    retention_set,
    baseline_retention_em: float,
    baseline_edit_em: float,
    state_before: Dict,
    lambda_forget: float = 1.0,
    lambda_drift: float = 0.01
) -> float:
    """
    Compute acceptance score for an edit.

    S = EditGain - λ₁·Forget - λ₂·||Δθ||
    """
    # Measure edit success (on single item for efficiency)
    current_answer = generate_answer(
        model, tokenizer,
        edit_item['question'],
        edit_item['context']
    )
    target_answer = edit_item['answers']['text'][0]

    # Simple word overlap as proxy for improvement
    current_words = set(current_answer.lower().split())
    target_words = set(target_answer.lower().split())
    overlap = len(current_words & target_words) / max(len(target_words), 1)
    edit_gain = overlap

    # Measure forgetting (sample retention set for speed)
    sample_size = min(20, len(retention_set))
    retention_sample = retention_set.select(range(sample_size))
    current_retention = compute_em_f1(model, tokenizer, retention_sample)
    forget_score = max(0, baseline_retention_em - current_retention['exact_match'])

    # Measure adapter drift
    state_after = backup_lora_state(model)
    drift = compute_adapter_drift(state_before, state_after)

    # Compute total score
    score = edit_gain - lambda_forget * forget_score - lambda_drift * drift

    return score

#### MAIN LOOP
def process_edit_batch(
    model,
    tokenizer,
    edit_batch,
    retention_set,
    safety_set,
    retention_basis: torch.Tensor,
    baseline_retention_em: float,
    baseline_retention_f1: float,
    baseline_safety_em: float,
    baseline_safety_f1: float,
    acceptance_threshold: float = 0.1,
    lr: float = 1e-5
) -> Dict:
    """
    Process a batch of edits with null-space projection and performance-based safety filtering.

    Safety filtering prevents:
    1. Edits that cause output degradation (degenerate outputs)
    2. Edits that significantly hurt performance on retention/safety sets

    Rollback facility:
    - Every edit is applied to a temporary backup
    - If safety checks fail, weights are restored
    - Only accepted edits persist

    Returns:
        Dictionary with results and metrics
    """
    results = {
        'total': len(edit_batch),
        'accepted': 0,
        'rejected_safety': 0,
        'rejected_score': 0,
        'candidates': []
    }

    model.train()

    # Phase 1: Generate and project gradients
    print("\n=== Phase 1: Gradient Computation & Projection ===")
    candidates = []

    for item in tqdm(edit_batch, desc="Computing edit gradients"):
        # Compute raw gradient
        grad = compute_edit_gradient(model, tokenizer, item)

        # Project to null space
        grad_proj = project_to_null_space(grad, retention_basis)

        candidate = EditCandidate(
            item=item,
            gradient=grad,
            projected_gradient=grad_proj
        )
        candidates.append(candidate)

    # Phase 2: Pre-edit output quality checks
    print("\n=== Phase 2: Pre-Edit Output Quality Checks ===")
    for candidate in tqdm(candidates, desc="Checking output quality"):
        # Generate answer with current model
        answer = generate_answer(
            model, tokenizer,
            candidate.item['question'],
            candidate.item['context']
        )

        # Check for degenerate outputs
        safe, reason = check_output_safety(answer)
        candidate.safe = safe
        candidate.safety_reason = reason

        if not safe:
            results['rejected_safety'] += 1
            print(f"  ✗ Pre-edit rejection: {reason}")

    # Phase 3: Apply, test, and score edits (WITH ROLLBACK)
    print("\n=== Phase 3: Edit Application with Performance Safety & Rollback ===")
    for i, candidate in enumerate(tqdm(candidates, desc="Testing edits")):
        if not candidate.safe:
            continue

        # Rollback - Backup state before edit
        state_backup = backup_lora_state(model)

        # Apply projected update temporarily
        apply_projected_update(model, candidate.projected_gradient, lr=lr)

        # SAFETY CHECK 1: Performance on safety set
        safe, reason = check_behavioral_safety(
            model, tokenizer, safety_set,
            baseline_safety_em,
            baseline_safety_f1,
            em_threshold=10.0,  # Max 10 point drop
            f1_threshold=10.0
        )

        if not safe:
            candidate.safe = False
            candidate.safety_reason = reason
            results['rejected_safety'] += 1
            # Rollback -  Restore previous weights
            restore_lora_state(model, state_backup)
            print(f"  ✗ Edit {i+1}: ROLLED BACK - {reason}")
            continue

        # SAFETY CHECK 2: Performance on retention set
        retention_sample = retention_set.select(range(min(20, len(retention_set))))
        retention_check = compute_em_f1(model, tokenizer, retention_sample)
        retention_drop = baseline_retention_em - retention_check['exact_match']

        if retention_drop > 15.0:  # Max 15 point drop on retention
            candidate.safe = False
            candidate.safety_reason = f"Retention performance dropped by {retention_drop:.2f} points"
            results['rejected_safety'] += 1
            # Rollback -  Restore previous weights
            restore_lora_state(model, state_backup)
            print(f"  ✗ Edit {i+1}: ROLLED BACK - Retention degradation")
            continue

        #  SAFETY CHECK 3: Output quality after edit
        test_answer = generate_answer(
            model, tokenizer,
            candidate.item['question'],
            candidate.item['context']
        )
        safe, reason = check_output_safety(test_answer)

        if not safe:
            candidate.safe = False
            candidate.safety_reason = f"Post-edit output degraded: {reason}"
            results['rejected_safety'] += 1
            # Rollback -  Restore previous weights
            restore_lora_state(model, state_backup)
            print(f"  ✗ Edit {i+1}: ROLLED BACK - Output degradation")
            continue

        # safety checks passed, now score the edit
        score = score_edit(
            model, tokenizer, candidate.item,
            retention_set, baseline_retention_em,
            baseline_edit['exact_match'],
            state_backup
        )
        candidate.score = score

        # Accept or reject based on score threshold
        if score > acceptance_threshold:
            results['accepted'] += 1
            print(f"Edit {i+1}: ACCEPTED (score={score:.3f})")
            # Edit is kept - no rollback
        else:
            results['rejected_score'] += 1
            # Rollback -  Restore previous weights
            restore_lora_state(model, state_backup)
            print(f"Edit {i+1}: ROLLED BACK - Low score ({score:.3f})")

    results['candidates'] = candidates
    return results

BATCH_SIZE = 8
edit_batch = edit_set.select(range(BATCH_SIZE))

print("="*60)
print("EXPERIMENT: Constrained Edits with Performance Safety")
print("="*60)
print("\nSafety Features:")
print("  1. Pre-edit output quality checks")
print("  2. Post-edit performance validation")
print("  3. Automatic rollback on failures")
print("  4. Retention set performance monitoring")
print("="*60)

# Run constrained editing with performance-based safety
results_constrained = process_edit_batch(
    model=model,
    tokenizer=tokenizer,
    edit_batch=edit_batch,
    retention_set=retention_set,
    safety_set=safety_set,
    retention_basis=retention_basis,
    baseline_retention_em=baseline_retention['exact_match'],
    baseline_retention_f1=baseline_retention['f1'],
    baseline_safety_em=baseline_safety['exact_match'],
    baseline_safety_f1=baseline_safety['f1'],
    acceptance_threshold=0.1,
    lr=1e-5
)

print("\n" + "="*60)
print("RESULTS SUMMARY")
print("="*60)
print(f"Total edits processed: {results_constrained['total']}")
print(f"Accepted (committed): {results_constrained['accepted']}")
print(f"Rejected (performance safety): {results_constrained['rejected_safety']}")
print(f"Rejected (low score): {results_constrained['rejected_score']}")
print(f"\nRollback events: {results_constrained['rejected_safety'] + results_constrained['rejected_score']}")

print("\n" + "="*60)
print("POST-EDIT EVALUATION")
print("="*60)

# Evaluate on retention set
print("\nRetention Set:")
final_retention = compute_em_f1(model, tokenizer, retention_set)
print(f"  Baseline EM: {baseline_retention['exact_match']:.2f}")
print(f"  Final EM: {final_retention['exact_match']:.2f}")
print(f"  Δ EM: {final_retention['exact_match'] - baseline_retention['exact_match']:.2f}")
print(f"  Baseline F1: {baseline_retention['f1']:.2f}")
print(f"  Final F1: {final_retention['f1']:.2f}")
print(f"  Δ F1: {final_retention['f1'] - baseline_retention['f1']:.2f}")

# Evaluate on edit set
print("\nEdit Set:")
final_edit = compute_em_f1(model, tokenizer, edit_set)
print(f"  Baseline EM: {baseline_edit['exact_match']:.2f}")
print(f"  Final EM: {final_edit['exact_match']:.2f}")
print(f"  Δ EM: {final_edit['exact_match'] - baseline_edit['exact_match']:.2f}")
print(f"  Baseline F1: {baseline_edit['f1']:.2f}")
print(f"  Final F1: {final_edit['f1']:.2f}")
print(f"  Δ F1: {final_edit['f1'] - baseline_edit['f1']:.2f}")

# Evaluate on safety set
print("\nSafety Set:")
final_safety = compute_em_f1(model, tokenizer, safety_set)
print(f"  Baseline EM: {baseline_safety['exact_match']:.2f}")
print(f"  Final EM: {final_safety['exact_match']:.2f}")
print(f"  Δ EM: {final_safety['exact_match'] - baseline_safety['exact_match']:.2f}")

import matplotlib.pyplot as plt

# Prepare data
metrics = ['EM', 'F1']
sets = ['Retention', 'Edit', 'Safety']

baseline_scores = [
    [baseline_retention['exact_match'], baseline_retention['f1']],
    [baseline_edit['exact_match'], baseline_edit['f1']],
    [baseline_safety['exact_match'], baseline_safety['f1']]
]

final_scores = [
    [final_retention['exact_match'], final_retention['f1']],
    [final_edit['exact_match'], final_edit['f1']],
    [final_safety['exact_match'], final_safety['f1']]
]

# Create bar plot
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for i, metric in enumerate(metrics):
    ax = axes[i]

    x = np.arange(len(sets))
    width = 0.35

    baseline_vals = [s[i] for s in baseline_scores]
    final_vals = [s[i] for s in final_scores]

    ax.bar(x - width/2, baseline_vals, width, label='Baseline', alpha=0.8)
    ax.bar(x + width/2, final_vals, width, label='After Edits', alpha=0.8)

    ax.set_ylabel(f'{metric} Score')
    ax.set_title(f'{metric} Comparison')
    ax.set_xticks(x)
    ax.set_xticklabels(sets)
    ax.legend()
    ax.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.show()

print("="*60)
print("FINAL ANALYSIS")
print("="*60)

# Compute forgetting metrics
retention_em_drop = baseline_retention['exact_match'] - final_retention['exact_match']
retention_f1_drop = baseline_retention['f1'] - final_retention['f1']

edit_em_gain = final_edit['exact_match'] - baseline_edit['exact_match']
edit_f1_gain = final_edit['f1'] - baseline_edit['f1']

print("\nKey Metrics:")
print(f"\n1. Retention Preservation:")
print(f"   - EM drop: {retention_em_drop:.2f}")
print(f"   - F1 drop: {retention_f1_drop:.2f}")
print(f"   - Status: {'PRESERVED' if abs(retention_em_drop) < 5 else 'DEGRADED'}")

print(f"\n2. Edit Success:")
print(f"   - EM gain: {edit_em_gain:.2f}")
print(f"   - F1 gain: {edit_f1_gain:.2f}")
print(f"   - Acceptance rate: {results_constrained['accepted']/results_constrained['total']*100:.1f}%")

print(f"\n3. Safety & Rollback:")
print(f"   - Safety rejections: {results_constrained['rejected_safety']}")
print(f"   - Score rejections: {results_constrained['rejected_score']}")
print(f"   - Total rollbacks: {results_constrained['rejected_safety'] + results_constrained['rejected_score']}")

print("\n" + "="*60)
print("CONCLUSIONS")
print("="*60)

if abs(retention_em_drop) < 5 and results_constrained['accepted'] > 0:
    print("\nSUCCESS: Null-space projection preserved knowledge while allowing edits")
    print("   - Retention metrics remained stable")
    print("   - Some edits were successfully applied")
    print("   - Safety filters prevented performance degradation")
    print("   - Rollback facility protected model integrity")
elif abs(retention_em_drop) >= 5:
    print("\n WARNING: Significant knowledge degradation detected")
    print("   - Consider: increasing k, reducing learning rate, or using stronger constraints")
else:
    print("\n PARTIAL SUCCESS: Knowledge preserved but few edits accepted")
    print("   - Consider: relaxing acceptance threshold or improving edit quality")

print("\n" + "="*60)

RUN_UNCONSTRAINED_COMPARISON = True  # Set to False to skip

if RUN_UNCONSTRAINED_COMPARISON:
    print("="*60)
    print("RUNNING UNCONSTRAINED EDIT COMPARISON")
    print("="*60)
    print("\nThis will show catastrophic forgetting without projection...\n")

    # Reload fresh model
    model_unconstrained = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        trust_remote_code=True
    )
    model_unconstrained = get_peft_model(model_unconstrained, lora_config)

    # Freeze base, keep only LoRA trainable
    for name, param in model_unconstrained.named_parameters():
        if 'lora' not in name:
            param.requires_grad = False

    # Use .select() to get a proper subset that iterates item-by-item
    unconstrained_edit_subset = edit_batch.select(range(8))

    # Apply unconstrained edits (raw gradients, no null-space projection)
    for item in tqdm(unconstrained_edit_subset, desc="Unconstrained edits"):
        grad = compute_edit_gradient(model_unconstrained, tokenizer, item)
        apply_projected_update(model_unconstrained, grad, lr=1e-6)  # Higher LR to amplify effect

    # Evaluate unconstrained model
    print("\nEvaluating unconstrained model...")
    unconstrained_retention = compute_em_f1(model_unconstrained, tokenizer, retention_set)
    unconstrained_edit = compute_em_f1(model_unconstrained, tokenizer, edit_set)

    # Compute forgetting scores
    unconstrained_forget = baseline_retention['exact_match'] - unconstrained_retention['exact_match']
    constrained_forget = baseline_retention['exact_match'] - final_retention['exact_match']

    print("\n" + "="*60)
    print("CONSTRAINED vs UNCONSTRAINED COMPARISON")
    print("="*60)

    print("\nUnconstrained (raw gradients, no projection):")
    print(f"  Retention EM: {baseline_retention['exact_match']:.2f} → {unconstrained_retention['exact_match']:.2f}  (Δ {-unconstrained_forget:.2f})")
    print(f"  Retention F1: {baseline_retention['f1']:.2f} → {unconstrained_retention['f1']:.2f}")
    print(f"  Edit EM:      {baseline_edit['exact_match']:.2f} → {unconstrained_edit['exact_match']:.2f}")
    print(f"  Forgetting:   {unconstrained_forget:.2f} points")

    print("\nConstrained (null-space projected gradients):")
    print(f"  Retention EM: {baseline_retention['exact_match']:.2f} → {final_retention['exact_match']:.2f}  (Δ {-constrained_forget:.2f})")
    print(f"  Retention F1: {baseline_retention['f1']:.2f} → {final_retention['f1']:.2f}")
    print(f"  Edit EM:      {baseline_edit['exact_match']:.2f} → {final_edit['exact_match']:.2f}")
    print(f"  Forgetting:   {constrained_forget:.2f} points")

    print("\n" + "="*60)
    print("VERDICT")
    print("="*60)
    if constrained_forget < unconstrained_forget:
        print(f"\n Null-space projection reduced forgetting by {unconstrained_forget - constrained_forget:.2f} points")
        print(f"   Unconstrained forgot {unconstrained_forget:.2f} pts vs Constrained {constrained_forget:.2f} pts")
    else:
        print(f"\n  Both methods showed similar forgetting — consider increasing k or lowering lr")

    # ===================================================================
    # GRAPHS
    # ===================================================================
    import matplotlib.pyplot as plt
    import matplotlib.gridspec as gridspec

    fig = plt.figure(figsize=(18, 14))
    gs = gridspec.GridSpec(2, 3, hspace=0.35, wspace=0.3)

    color_baseline = '#4A90D9'
    color_constrained = '#27AE60'
    color_unconstrained = '#E74C3C'

    # ---------- Graph 1: EM side-by-side across all three sets ----------
    ax1 = fig.add_subplot(gs[0, 0])
    sets_labels = ['Retention', 'Edit', 'Safety']
    baseline_ems = [
        baseline_retention['exact_match'],
        baseline_edit['exact_match'],
        baseline_safety['exact_match']
    ]
    constrained_ems = [
        final_retention['exact_match'],
        final_edit['exact_match'],
        final_safety['exact_match']
    ]
    unconstrained_ems = [
        unconstrained_retention['exact_match'],
        unconstrained_edit['exact_match'],
        baseline_safety['exact_match']  # unconstrained safety not evaluated separately
    ]

    x = np.arange(len(sets_labels))
    w = 0.25
    ax1.bar(x - w, baseline_ems, w, label='Baseline', color=color_baseline, alpha=0.85)
    ax1.bar(x,     constrained_ems, w, label='Constrained', color=color_constrained, alpha=0.85)
    ax1.bar(x + w, unconstrained_ems, w, label='Unconstrained', color=color_unconstrained, alpha=0.85)
    ax1.set_ylabel('Exact Match Score')
    ax1.set_title('Exact Match Across Sets')
    ax1.set_xticks(x)
    ax1.set_xticklabels(sets_labels)
    ax1.legend(fontsize=8)
    ax1.grid(axis='y', alpha=0.3)

    # ---------- Graph 2: F1 side-by-side across Retention & Edit ----------
    ax2 = fig.add_subplot(gs[0, 1])
    f1_sets = ['Retention', 'Edit']
    baseline_f1s = [
        baseline_retention['f1'],
        baseline_edit['f1']
    ]
    constrained_f1s = [
        final_retention['f1'],
        final_edit['f1']
    ]
    unconstrained_f1s = [
        unconstrained_retention['f1'],
        unconstrained_edit['f1']
    ]

    x2 = np.arange(len(f1_sets))
    ax2.bar(x2 - w, baseline_f1s, w, label='Baseline', color=color_baseline, alpha=0.85)
    ax2.bar(x2,     constrained_f1s, w, label='Constrained', color=color_constrained, alpha=0.85)
    ax2.bar(x2 + w, unconstrained_f1s, w, label='Unconstrained', color=color_unconstrained, alpha=0.85)
    ax2.set_ylabel('F1 Score')
    ax2.set_title('F1 Across Retention & Edit Sets')
    ax2.set_xticks(x2)
    ax2.set_xticklabels(f1_sets)
    ax2.legend(fontsize=8)
    ax2.grid(axis='y', alpha=0.3)

    # ---------- Graph 3: Forgetting Score (the core result) ----------
    ax3 = fig.add_subplot(gs[0, 2])
    forget_labels = ['Constrained\n(Null-Space)', 'Unconstrained\n(Raw Gradient)']
    forget_values = [constrained_forget, unconstrained_forget]
    forget_colors = [color_constrained, color_unconstrained]
    bars = ax3.bar(forget_labels, forget_values, color=forget_colors, alpha=0.85, width=0.5)
    ax3.set_ylabel('Forgetting (EM Points Lost)')
    ax3.set_title('Forgetting Score Comparison')
    ax3.grid(axis='y', alpha=0.3)
    # Annotate values on bars
    for bar, val in zip(bars, forget_values):
        ax3.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.3,
                 f'{val:.2f}', ha='center', va='bottom', fontweight='bold', fontsize=11)

    # ---------- Graph 4: Retention EM trajectory (before → after) ----------
    ax4 = fig.add_subplot(gs[1, 0])
    stages = ['Baseline', 'After Edits']
    constrained_trajectory = [baseline_retention['exact_match'], final_retention['exact_match']]
    unconstrained_trajectory = [baseline_retention['exact_match'], unconstrained_retention['exact_match']]

    ax4.plot(stages, constrained_trajectory, marker='o', color=color_constrained,
             linewidth=2.5, markersize=9, label='Constrained')
    ax4.plot(stages, unconstrained_trajectory, marker='s', color=color_unconstrained,
             linewidth=2.5, markersize=9, label='Unconstrained')
    ax4.axhline(y=baseline_retention['exact_match'], color=color_baseline,
                linestyle='--', alpha=0.5, label='Baseline level')
    ax4.set_ylabel('Retention EM')
    ax4.set_title('Retention EM: Before vs After Edits')
    ax4.legend(fontsize=8)
    ax4.grid(alpha=0.3)

    # ---------- Graph 5: Retention F1 trajectory (before → after) ----------
    ax5 = fig.add_subplot(gs[1, 1])
    constrained_f1_trajectory = [baseline_retention['f1'], final_retention['f1']]
    unconstrained_f1_trajectory = [baseline_retention['f1'], unconstrained_retention['f1']]

    ax5.plot(stages, constrained_f1_trajectory, marker='o', color=color_constrained,
             linewidth=2.5, markersize=9, label='Constrained')
    ax5.plot(stages, unconstrained_f1_trajectory, marker='s', color=color_unconstrained,
             linewidth=2.5, markersize=9, label='Unconstrained')
    ax5.axhline(y=baseline_retention['f1'], color=color_baseline,
                linestyle='--', alpha=0.5, label='Baseline level')
    ax5.set_ylabel('Retention F1')
    ax5.set_title('Retention F1: Before vs After Edits')
    ax5.legend(fontsize=8)
    ax5.grid(alpha=0.3)

    # ---------- Graph 6: Radar-style summary table as a stacked comparison ----------
    ax6 = fig.add_subplot(gs[1, 2])
    ax6.axis('off')
    table_data = [
        ['Metric',              'Baseline',  'Constrained',  'Unconstrained'],
        ['Retention EM',        f"{baseline_retention['exact_match']:.2f}",
                                f"{final_retention['exact_match']:.2f}",
                                f"{unconstrained_retention['exact_match']:.2f}"],
        ['Retention F1',        f"{baseline_retention['f1']:.2f}",
                                f"{final_retention['f1']:.2f}",
                                f"{unconstrained_retention['f1']:.2f}"],
        ['Edit EM',             f"{baseline_edit['exact_match']:.2f}",
                                f"{final_edit['exact_match']:.2f}",
                                f"{unconstrained_edit['exact_match']:.2f}"],
        ['Edit F1',             f"{baseline_edit['f1']:.2f}",
                                f"{final_edit['f1']:.2f}",
                                f"{unconstrained_edit['f1']:.2f}"],
        ['Forgetting (EM pts)', '—',
                                f"{constrained_forget:.2f}",
                                f"{unconstrained_forget:.2f}"],
    ]

    table = ax6.table(
        cellText=[row for row in table_data[1:]],
        colLabels=table_data[0],
        loc='center',
        cellLoc='center'
    )
    table.auto_set_font_size(False)
    table.set_fontsize(9)
    table.scale(1.1, 1.6)

    # Style header row
    for col in range(4):
        cell = table[0, col]
        cell.set_facecolor('#2C3E50')
        cell.set_text_props(color='white', fontweight='bold')

    # Style data rows - highlight constrained (green tint) vs unconstrained (red tint)
    for row in range(1, len(table_data) - 1):
        table[row, 0].set_facecolor('#ECF0F1')  # metric label column
        table[row, 1].set_facecolor('#D6EAF8')  # baseline column
        table[row, 2].set_facecolor('#D5F5E3')  # constrained column (green tint)
        table[row, 3].set_facecolor('#FADBD8')  # unconstrained column (red tint)

    ax6.set_title('Summary Table', pad=20, fontsize=11, fontweight='bold')

    fig.suptitle('Enhanced SEAL Phase 2: Constrained vs Unconstrained Edit Comparison',
                 fontsize=15, fontweight='bold', y=1.01)

    plt.savefig('seal_comparison.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("\nComparison graphs saved to seal_comparison.png")

    # Cleanup
    del model_unconstrained
    torch.cuda.empty_cache()
    print("Unconstrained model freed from memory")
else:
    print("Unconstrained comparison disabled. Set RUN_UNCONSTRAINED_COMPARISON=True to enable.")